/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CodigoPOO;

import javax.swing.JOptionPane;

/**
 *
 * @author julio
 */
public class Exercicio15_INTERFACE extends javax.swing.JFrame {

    /**
     * Creates new form Exercicio15_INTERFACE
     */
    public Exercicio15_INTERFACE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDiasAPagar = new javax.swing.JLabel();
        txtDiasAPagar = new javax.swing.JTextField();
        lblTotalAPagar = new javax.swing.JLabel();
        txtTotalAPagar = new javax.swing.JTextField();
        txtDiasAlugados = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblTitulo = new javax.swing.JLabel();
        btnCalcularTotalAPagar = new javax.swing.JButton();
        btnCalcularKmAPagar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        sliDiasAlugados = new javax.swing.JSlider();
        txtKm = new javax.swing.JTextField();
        txtKmAPagar = new javax.swing.JTextField();
        lblKmAPagar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aluguel de Carro");

        lblDiasAPagar.setText("Valor a pagar: R$");

        txtDiasAPagar.setEditable(false);
        txtDiasAPagar.setText("0");

        lblTotalAPagar.setText("Total: R$");

        txtTotalAPagar.setEditable(false);
        txtTotalAPagar.setText("0");

        txtDiasAlugados.setEditable(false);
        txtDiasAlugados.setText("0");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("Exercicio15: Calculador de valor (KM e Aluguel de carro)");

        btnCalcularTotalAPagar.setBackground(new java.awt.Color(102, 153, 0));
        btnCalcularTotalAPagar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCalcularTotalAPagar.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcularTotalAPagar.setText("Calcular");
        btnCalcularTotalAPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularTotalAPagarActionPerformed(evt);
            }
        });

        btnCalcularKmAPagar.setBackground(new java.awt.Color(0, 153, 102));
        btnCalcularKmAPagar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCalcularKmAPagar.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcularKmAPagar.setText("Calcular");
        btnCalcularKmAPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularKmAPagarActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(102, 0, 0));
        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        sliDiasAlugados.setMaximum(31);
        sliDiasAlugados.setValue(0);
        sliDiasAlugados.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliDiasAlugadosStateChanged(evt);
            }
        });

        txtKm.setText("0");

        txtKmAPagar.setEditable(false);
        txtKmAPagar.setText("0");

        lblKmAPagar.setText("Valor a pagar: R$");

        jLabel2.setText("Dias Alugados:");

        jLabel4.setText("KMs Percorridos:");

        jLabel6.setText("KMs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtKm, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblKmAPagar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtKmAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(btnCalcularKmAPagar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sliDiasAlugados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDiasAlugados, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDiasAPagar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDiasAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(248, 248, 248))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(lblTotalAPagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(btnCalcularTotalAPagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(300, 300, 300))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblTitulo)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sliDiasAlugados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtDiasAlugados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiasAPagar)
                    .addComponent(txtDiasAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKmAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKmAPagar)
                    .addComponent(btnCalcularKmAPagar))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalAPagar)
                    .addComponent(txtTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularTotalAPagar)
                    .addComponent(btnLimpar))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Instanciando um novo objeto    
    Exercicio15_CLASSE obj = new Exercicio15_CLASSE();
    
    private void btnCalcularTotalAPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTotalAPagarActionPerformed
        // TODO add your handling code here: BOTAO CALCULAR
        
        //Chamando um metodo que irá calcular o valor total a pagar
        obj.calcularTotal();
        
        //Inserindo a uma caixa de texto o valor total a pagar de acordo com o resultado do metodo acima
        txtTotalAPagar.setText(String.format("%.2f", obj.getTotalAPagar()));

    }//GEN-LAST:event_btnCalcularTotalAPagarActionPerformed

    private void btnCalcularKmAPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularKmAPagarActionPerformed
        // TODO add your handling code here: BOTAO CALCULAR VALOR A PAGAR POR KM
        
        //Inserindo a um Setter de um atributo de classe o valor km inserido em uma caixa de texto
        obj.setKmPercorrido(Double.parseDouble(txtKm.getText()));

        //Chamando um metodo que irá calcular o valor a pagar de acordo com a quantidade de KMs percorridos
        obj.calcularKM();
        
        //Inserindo a uma caixa de texto o valor a pagar de acordo com o resultado do metodo acima
        txtKmAPagar.setText(String.format("%.2f",obj.getKmAPagar()));

    }//GEN-LAST:event_btnCalcularKmAPagarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here: BOTAO LIMPAR

        //Limpando as caixas de texto e inserindo valores padrão ao limpar
        
        //Chamando um metodo que irá zerar os valores abaixo
        obj.zerarValoresKM();
        
        //Usando do metodo acima para limparmos as caixa de texto e setando as mesmas para um valor padrão de 0
        txtKm.setText(String.format("%.0f",obj.getKmPercorrido()));
        txtKmAPagar.setText(String.format("%.0f",obj.getKmAPagar()));
        txtTotalAPagar.setText(null);
        
    }//GEN-LAST:event_btnLimparActionPerformed

    private void sliDiasAlugadosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliDiasAlugadosStateChanged
        // TODO add your handling code here: SLIDER DIAS ALUGADOS
        
        //Inserindo a uma caixa de texto o valor de uma Slider
        txtDiasAlugados.setText(String.valueOf(sliDiasAlugados.getValue()));
        
        //Inserido a um Setter de um atributo de classe o valor da caixa de texto acima
        obj.setDiasAlugados(Integer.parseInt(txtDiasAlugados.getText()));
        
        //Chamando um metodo que irá calcular o valor a pagar de acordo com a quantidade de dias alugados acima
        obj.calcularDias();
        //Atribuindo o valor a pagar de acordo com o resultado de calculo no metodo acima em uma caixa de texto 
        txtDiasAPagar.setText(String.format("%.2f",obj.getDiasAPagar()));        

    }//GEN-LAST:event_sliDiasAlugadosStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio15_INTERFACE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio15_INTERFACE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio15_INTERFACE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio15_INTERFACE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicio15_INTERFACE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularKmAPagar;
    private javax.swing.JButton btnCalcularTotalAPagar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDiasAPagar;
    private javax.swing.JLabel lblKmAPagar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotalAPagar;
    private javax.swing.JSlider sliDiasAlugados;
    private javax.swing.JTextField txtDiasAPagar;
    private javax.swing.JTextField txtDiasAlugados;
    private javax.swing.JTextField txtKm;
    private javax.swing.JTextField txtKmAPagar;
    private javax.swing.JTextField txtTotalAPagar;
    // End of variables declaration//GEN-END:variables
}
